### ISSUE TITLE
What is the max macOS Version support?

### ISSUE THREAD

**Issue by JosueAshton** [Austcool-Walker/Dell-Optiplex-760-hackintosh-OpenCore#1]
Compatibility Catalina or Big Sur?

**Comment by Austcool-Walker** [comment]
I am not sure I got doxed 8 months ago and no longer have the Dell Optiplex 760 do to getting removed from the internet I have no idea if it works with anything other then big sur.

**Comment by Austcool-Walker** [comment]
you can try tho; I'd love to see if it works! If it does work let me know and I'll mark the issue solved.

**Comment by abdallahhelmy99** [comment]
internet not working in sierra and high sierra and el capitan but still can't find out if it is working on big sur

**Comment by Austcool-Walker** [comment]
I no longer own/have this computer this project is E0L
